apiVersion: v1
kind: Service
metadata:
  name: schedule-api-service
  labels:
    app: schedule-api
spec:
  selector:
    app: schedule-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-api-deployment
  labels:
    app: schedule-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-api
  template:
    metadata:
      labels:
        app: schedule-api
    spec:
      containers:
        - name: schedule-api
          image: docker.io/library/schedule-api-java:0.0.0
          imagePullPolicy: Never
          env:
            - name: REDIS_URL
              value: redis://cache-service.default.svc.cluster.local:6379
            - name: BASE_UI_URL
              value: http://localhost:3000
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
