apiVersion: v1
kind: Service
metadata:
  name: cache-service
  labels:
    app: cache
spec:
  selector:
    app: cache
  ports:
    - port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: redis
          image: redis:8.2
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "250m"
