apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: admin
      port: 8001
      targetPort: 8001
    - name: admin-ui
      port: 8002
      targetPort: 8002

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true

    services:
      - host: ui-service.default.svc.cluster.local
        name: ui-service
        port: 3000
        protocol: http
        routes:
          - name: index
            paths:
              - /
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              policy: local
      - host: api-service.default.svc.cluster.local
        name: api-service
        port: 8080
        protocol: http
        routes:
          - name: api
            paths:
              - /schedule/api
            strip_path: true
        plugins:
          - name: rate-limiting
            config:
              minute: 10
              policy: local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: kong/kong-gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/declarative/kong.yaml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_ADMIN_GUI_URL
              value: http://localhost:8002
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8002
          resources:
            limits:
              memory: "2048Mi"
              cpu: "2000m"
            requests:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - name: kong-declarative-config
              mountPath: /kong/declarative
      volumes:
        - name: kong-declarative-config
          configMap:
            name: gateway-configmap
