apiVersion: v1
kind: Service
metadata:
  name: api-service-{{ .Release.Name }}
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-{{ .Release.Name }}
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-{{ .Release.Name }}
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: REDIS_URL
              value: redis://cache-service-{{ .Release.Name }}.default.svc.cluster.local:6379
            - name: BASE_UI_URL
              value: {{ .Values.api.base_ui_url }}
          resources:
            limits:
              memory: {{ .Values.api.limits.memory }}
              cpu: {{ .Values.api.limits.cpu }}
            requests:
              memory: {{ .Values.api.requests.memory }}
              cpu: {{ .Values.api.requests.cpu }}
          ports:
            - containerPort: {{ .Values.api.port }}
